---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcCidrBlock:
    Type: String
    Description: CidrBlock for the VPC
    Default: 10.0.0.0/24
  PrivateSubnetCidrBlock:
    Type: String
    Description: CidrBlock for private subnet
    Default: 10.0.0.0/25
  PublicSubnetCidrBlock:
    Type: String
    Description: CidrBlock for public subnet
    Default: 10.0.0.128/25
  AvailabilityZone:
    Type: String
    Description: Availability Zone where the subnets and wordpress instance should
      be created. For example, us-east-1a, us-east-1b etc.
  KeyPairName:
    Type: String
    Description: Name of private key pair in Ec2 to be used for SSHing into the instance
Resources:
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidrBlock
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: Wordpress_VPC
  internetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}
  dhcpOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: ec2.internal
      DomainNameServers:
      - AmazonProvidedDNS
  internetGatewayRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: vpc
  natGatewayRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: vpc
  natGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId:
        Ref: publicSubnet
      AllocationId:
        Fn::GetAtt:
        - elasticIp
        - AllocationId
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Blueprint Wordpress demo
      VpcId:
        Ref: vpc
  networkAclEntryEgress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: '1'
      NetworkAclId:
        Fn::GetAtt:
        - vpc
        - DefaultNetworkAcl
  networkAclEntryIngress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'false'
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: '1'
      NetworkAclId:
        Fn::GetAtt:
        - vpc
        - DefaultNetworkAcl
  vpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: vpc
      InternetGatewayId:
        Ref: internetGateway
  internetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: internetGatewayRouteTable
      GatewayId:
        Ref: internetGateway
    DependsOn: vpcGatewayAttachment
  elasticIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  natGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: natGatewayRouteTable
      NatGatewayId:
        Ref: natGateway
  vpcDhcpOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId:
        Ref: vpc
      DhcpOptionsId:
        Ref: dhcpOptions
  sshIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: securityGroup
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  httpIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: securityGroup
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 0.0.0.0/0
  withinSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: securityGroup
      IpProtocol: "-1"
      SourceSecurityGroupId:
        Ref: securityGroup
  egress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Ref: securityGroup
      IpProtocol: "-1"
      CidrIp: 0.0.0.0/0
  privateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: PrivateSubnetCidrBlock
      AvailabilityZone:
        Ref: AvailabilityZone
      VpcId:
        Ref: vpc
  publicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: PublicSubnetCidrBlock
      AvailabilityZone:
        Ref: AvailabilityZone
      VpcId:
        Ref: vpc
      MapPublicIpOnLaunch: 'true'
  privateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: natGatewayRouteTable
      SubnetId:
        Ref: privateSubnet
  publicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: internetGatewayRouteTable
      SubnetId:
        Ref: publicSubnet
  wordpressInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZone
      ImageId: ami-0f8a61b5d58fa695d
      InstanceType: t2.micro
      KeyName:
        Ref: KeyPairName
      NetworkInterfaces:
      - AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        GroupSet:
        - Ref: securityGroup
        SubnetId:
          Ref: publicSubnet
      UserData:
        Fn::Base64:
          Fn::Join:
          - "\n"
          - - "#!/bin/bash -ex"
            - PUBLIC_IPv4=`(curl http://169.254.169.254/latest/meta-data/public-ipv4)`
            - mysql -u root -pamazonaws <<EOF
            - set @public_ip='${PUBLIC_IPv4}';
            - use wordpress;
            - UPDATE wp_options SET option_value = replace(option_value,'localhost',
              @public_ip) WHERE option_name = 'home' OR option_name = 'siteurl';
            - UPDATE wp_posts SET post_content = replace(post_content, 'localhost',@public_ip);
            - UPDATE wp_postmeta SET meta_value = replace(meta_value,'localhost',@public_ip);
            - UPDATE wp_usermeta SET meta_value = replace(meta_value, 'localhost',@public_ip);
            - UPDATE wp_links SET link_url = replace(link_url, 'localhost',@public_ip);
            - UPDATE wp_comments SET comment_content = replace(comment_content ,'localhost',
              @public_ip);
            - EOF
    DependsOn:
    - vpcGatewayAttachment
  wordpressGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      ConnectionInput:
        Name: wordpressGlueConnection
        ConnectionType: JDBC
        PhysicalConnectionRequirements:
          AvailabilityZone:
            Ref: AvailabilityZone
          SecurityGroupIdList:
          - Ref: securityGroup
          SubnetId:
            Ref: privateSubnet
        ConnectionProperties:
          JDBC_CONNECTION_URL:
            Fn::Join:
            - ''
            - - jdbc:mysql://
              - Fn::GetAtt:
                - wordpressInstance
                - PrivateIp
              - ":3306/wordpress"
          USERNAME: root
          PASSWORD: amazonaws
  wordpressBlueprintRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      RoleName: WordpressBlueprintRole
Outputs:
  wordpressInstance:
    Description: The instance id of the word press instance
    Value:
      Ref: wordpressInstance
  wordpressInstancePublicIp:
    Description: The public IP address of the word press instance
    Value:
      Fn::GetAtt:
      - wordpressInstance
      - PublicIp
  wordpressBlogUrl:
    Description: The URL to access the WordPress blogs stored on the instance
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - wordpressInstance
          - PublicIp
  wordpressGlueConnection:
    Description: The Glue connection to connect to the Wordpress database over JDBC
    Value:
      Ref: wordpressGlueConnection
  wordpressBlueprintRole:
    Description: The role used to create a data importer
    Value:
      Ref: wordpressBlueprintRole

